# Generated by Django 4.1.3 on 2022-12-04 04:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=250)),
                ('currency', models.CharField(max_length=250)),
                ('rate', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.company')),
            ],
        ),
    ]
