# Generated by Django 4.1.3 on 2022-12-04 20:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_company_options_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='maxAge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='minAge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_schedule',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
