# Generated by Django 4.1.3 on 2022-12-05 22:31

import apps.models.job
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_vacancy_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='company/default_company_thumbnail.jpg', upload_to=apps.models.job.company_upload_to),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='thumbnail',
            field=models.ImageField(default='vacancy/default_vacancy_thumbnail.jpg', upload_to=apps.models.job.vacancy_upload_to),
        ),
    ]
